config-version = 2
start-at-login = false
after-startup-command = ['enable off']
default-root-container-layout = 'tiles'
default-root-container-orientation = 'horizontal'
persistent-workspaces = ['Terminals']
[mode.main.binding]
[mode.active.binding]
cmd-left = 'focus left'
cmd-right = 'focus right'
cmd-up = 'focus up'
cmd-down = 'focus down'
cmd-shift-left = 'swap left'
cmd-shift-right = 'swap right'
cmd-shift-up = 'swap up'
cmd-shift-down = 'swap down'
cmd-minus = 'resize smart -50'
cmd-equal = 'resize smart +50'
cmd-f = 'fullscreen'
cmd-enter = "exec-and-forget open 'agent-control-center://new'"
ctrl-alt-4 = "exec-and-forget open 'agent-control-center://four'"
ctrl-alt-6 = "exec-and-forget open 'agent-control-center://six'"
ctrl-alt-esc = "exec-and-forget open 'agent-control-center://exit'"
ctrl-alt-p = "exec-and-forget open 'agent-control-center://pause'"
[gaps]
inner.horizontal = 8
inner.vertical = 8
outer.left = 8
outer.right = 8
outer.top = 8
outer.bottom = 8
[[on-window-detected]]
if = 'true'
run = 'layout floating'
